project:
  type: website
  output-dir: docs

website:
  title: "Stat Projects"
  description:
    A collection of projects I've done as a student at the Zicklin School of Business
  site-url: "https://github.com/charles-ramirez/stat-projects"
  navbar:
    background: primary
    search: false
    left: 
      - text: "Home"
      menu: 
        - text: "Project 1: Transit"
          href: project1.qmd
          
    tools:
      - icon: github
        href: https://github.com/charles-ramirez/
    
format:
  html:
    theme: cosmo
    toc: true